name: hive1
description: A sample command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.0 <3.0.0'


dependencies: 
  get: ^4.6.1
  hive: ^2.0.5

dev_dependencies:
  build_runner: ^2.1.7
  hive_generator: ^1.1.2
  lints: ^1.0.0
  test: ^1.16.0

